name: Daily Version Update

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}
  push:
    branches:
    - ci

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: VirtusLab/scala-cli-setup@v1.12
      - name: Run update script
        run: .github/scripts/update-build-version.sh
